spring:
  application:
    name: auth-service
  cloud:
    discovery:
      enabled: true

# Configuración de Keycloak
keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:8080}
  realm: ${KEYCLOAK_REALM:nutridata-realm}
  resource: ${KEYCLOAK_RESOURCE:auth-service}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
  bearer-only: true
  public-client: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://eureka:password@eureka-server:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

server:
  port: 8080
