services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - nutridata-network
    environment:
      - EUREKA_SERVER=${EUREKA_SERVER}
    env_file:
      - .env

networks:
    nutridata-network:
      external: true
