spring:
  application:
    name: patient
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database: postgresql
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      default_schema: patient
      ddl-auto: update
  cloud:
    discovery:
      enabled: false

eureka:
  client:
    enabled: false

server:
  port: 3200
