spring:
  application:
    name: patient
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database: postgresql
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      default_schema: patient
      ddl-auto: update
  cloud:
    discovery:
      enabled: false
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${COGNITO_CLIENT_ID}
            client-secret: ${COGNITO_CLIENT_SECRET}
            scope:
              - phone
              - openid
              - email
            # Spring Security by default uses a redirect-uri in the format: {baseUrl}/login/oauth2/code/{registrationId}
            # For example: http://localhost:8080/login/oauth2/code/cognito
            # See more: https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html#oauth2login-sample-redirect-uri
            redirect-uri: ${COGNITO_REDIRECT_URI}
        provider:
          cognito:
            issuerUri: ${COGNITO_ISSUER_URI}
            user-name-attribute: username

eureka:
  client:
    enabled: false

server:
  port: 3200
