services:
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - nutridata-network

networks:
  nutridata-network:
    external: true