spring:
  cloud:
    gateway:
      routes:
          - id: dashboard-route
            uri: ${DASHBOARD_URL:http://localhost:8080}
            predicates:
              - Path=/dashboard/**
            filters:
              - PrefixPath=/api
              - name: AddResponseHeader
                args:
                  name: X-Powered-By
                  value: NutriData Dashboard Gateway
          - id: patient-route
            uri: ${PATIENT_URL:http://localhost:3200}
            predicates:
              - Path=/patients/**
            filters:
              - PrefixPath=/api
              - name: AddResponseHeader
                args:
                  name: X-Powered-By
                  value: NutriData Patients Gateway
    config:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true