services:
  db:
    container_name: patient-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USERNAME: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
        - patient-db:/var/lib/postgresql/data

  app:
    container_name: patient-app
    image: patient-app
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "3200:3200"
    env_file:
      - .env
    environment:
        DATABASE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB} # db is the name of the service
        DATABASE_USERNAME: ${POSTGRES_USERNAME}
        DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
        - db
    networks:
        - nutridata-network

volumes:
    patient-db:

networks:
    nutridata-network:
      driver: bridge