services:
  db:
    container_name: patient-db
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        SPRING_DEVTOOLS_RESTART_ENABLED: true  # Enable DevTools for hot reloading
    volumes:
        - patient-db:/var/lib/postgresql/data
    networks:
      - nutridata-network

  app:
    container_name: patient-app
    image: patient-app
    build:
        context: .
        dockerfile: Dockerfile.dev
    ports:
        - "3200:3200"
    volumes:
        - ./src:/app/src
        - ./pom.xml:/app/pom.xml
    env_file:
      - .env
    environment:
        DATABASE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB} # db is the name of the service
        DATABASE_USERNAME: ${POSTGRES_USER}
        DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
        SPRING_DEVTOOLS_RESTART_ENABLED: true  # Enable DevTools for hot reloading
    depends_on:
        - db
    networks:
        - nutridata-network

volumes:
    patient-db:

networks:
  nutridata-network:
    external: true