spring:
  application:
    name: eureka-server

eureka:
    instance:
        hostname: eureka-server
    client:
        registerWithEureka: false
        fetchRegistry: false
        service-url:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761