spring:
  application:
    name: eureka-server
  security:
    user:
      name: eureka
      password: password

eureka:
    instance:
        hostname: eureka-server
    client:
        registerWithEureka: false
        fetchRegistry: false
        service-url:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

server:
  port: 8761