services:
  keycloak-db:
    container_name: keycloak-db
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB}
      POSTGRES_USER: ${KEYCLOAK_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_PASSWORD}
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    networks:
      - nutridata-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB}
      KC_DB_USERNAME: ${KEYCLOAK_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8181:8080"
    command: start-dev
    depends_on:
      - keycloak-db
    networks:
      - nutridata-network

  app:
    container_name: auth-app
    image: auth-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3201:3201"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    env_file:
      - .env
    environment:
      SPRING_DEVTOOLS_RESTART_ENABLED: true
      # Keycloak configuration for the auth service
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8181
      KEYCLOAK_REALM: nutridata
      KEYCLOAK_RESOURCE: auth-service
      KEYCLOAK_CREDENTIALS_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    depends_on:
      - keycloak
    networks:
      - nutridata-network

volumes:
  keycloak-db:

networks:
  nutridata-network:
    external: true